### ISSUE TITLE
'in' lookups do not work

### ISSUE THREAD

**Issue by yspanchal** [philipn/django-rest-framework-filters#16] opened 2015-02-16 11:02 UTC
can i use __in for multiple filters ?

**Comment by vinograd19** [comment] 2015-03-16 14:06
+

**Comment by sunbest** [comment] 2015-09-08 01:31
++

**Comment by aronysidoro** [comment] 2015-09-10 20:47
+1

**Comment by belugame** [comment] 2016-01-12 15:35
+1

**Comment by rpkilby** [comment] 2016-01-12 15:51
Hi, character and integer field types should be supported in the current release. eg, `?id__in=1,2,3`. The issue remains open because a more general solution could exist to support more field types (dates, datetimes). If you need a new field type to be supported, leave a comment here.

**Comment by belugame** [comment] 2016-01-12 16:07
@rpkilby Thank you :) I just installed the latest release. I'm using all-lookup filters on my fields but the __in=1,2 syntax gives me an empty list still. Does it only work with certain filter classes?

**Comment by rpkilby** [comment] 2016-01-12 17:10
@belugame There is an issue with the current release where the dict-style `ALL_LOOKUPS` shortcut accidentally bypasses the overrides. See #49 for more details. Until a new release is made, you may need to use an `AllLookupsFilter` instance.

**Comment by aronysidoro** [comment] 2016-01-12 17:20
All,

I ended up writing a simple ViewSet Mixin in order to be able to support the **IN** keyword.  This works for different types, not just *integers*.

Here is the mixin:

```python
class FilterRelatedMixin(object):
    """
    Allow filterable by 'IN' keyword.

    ``filter_fields``: A list of filterable fields that uses the 
    Django ORM sytax. Must be defined on the ModelViewSet that is 
    implementing this feature.
    """
    queryset = None
    filter_fields = None

    def get_queryset(self):
        queryset = super(FilterRelatedMixin, self).get_queryset()

        if self.filter_fields:
            kwargs = {}

            for param in self.request.query_params:
                if param.split("__")[0] in self.filter_fields:
                    if param.split("__")[-1] == "in":
                        value = self.request.query_params.get(param).split(',')
                    else:
                        value = self.request.query_params.get(param)

                    kwargs.update({param: value})

            queryset = queryset.filter(**kwargs)

        return queryset
```

To use this mixin, do:

```python

from rest_framework import viewsets

class MyViewSet(FilterRelatedMixin, viewsets.ModelViewSet):
    filter_fields = ('searchable model field one', 'two', 'etc',)
    # viewset code ...
```

**Comment by belugame** [comment] 2016-01-22 20:20
@aronysidoro That's pretty neat! In my use case for a small intranet application I just want to allow any sort of database lookup the ORM provides with small exceptions like on the user's password field. With your code and some adaptions I guess I can do that without specifying filter_fields on each viewset. Thank you! :+1:

**Comment by aronysidoro** [comment] 2016-01-25 20:23
@belugame, you can also use the django fields _meta api to return all model fields, which is what we commonly do, since it returns all fields and allows them to then be searchable, unless you want to limit searchable fields of course.  Here's the one liner:

```python
filter_fields = [f.name for f in model._meta.get_fields()]
```

**Comment by belugame** [comment] 2016-01-25 21:08
@aronysidoro yep, my initial approach was similiar:

    field_filters = dict((f, filters.ALL_LOOKUPS) for f in klass._meta.get_all_field_names())
but it didn't work with related lookup and __in

**Comment by rpkilby** [comment] 2016-01-27 21:56
@belugame my previous comments was slightly incorrect. The dict-style declarations are broken in the current release, where certain lookups (`in`, `isnull`) are **not** being overriden. The `ALL_LOOKUPS` const is broken in turn, as it's just a list of all the [SQL query terms](https://github.com/django/django/blob/master/django/db/models/sql/constants.py#L10-L15). This should be fixed on the current master branch - try installing that and see if the issue is fixed.

Related lookups are not able to be generated with the dict-style syntax, since they require a related filterset argument. You would need to manually create the `RelatedFilter` instance. eg,

```py
class FooFilter(filters.FilterSet):
    class Meta:
        fields = ['frobbles', 'widgets']

class BarFilter(filters.FilterSet):
    foo = filters.RelatedFilter('FooFilter')
```

**Comment by rpkilby** [comment] 2016-03-11 20:43
Hi all, django-filter v0.13.0 now supports `in` & `range` csv lookups, as well as date transforms. There should be a new drf-filters release soon (v0.8.0) that is compatible with these updates.

**Closed by rpkilby** 2016-03-11 20:43 UTC
