### ISSUE TITLE
New release django-filter change get_filter_name() method

### ISSUE THREAD

**Issue by Egregors** [philipn/django-rest-framework-filters#188] opened 2017-10-19 13:53 UTC
And we got `TypeError: get_filter_name() takes 2 positional arguments but 3 were given` exception:
```

manage.py@retail > check
bash -cl "/Users/egregors/Documents/Bitbucket/retail/env/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py check /Users/egregors/Documents/Bitbucket/retail"
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py", line 43, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/egregors/Documents/Bitbucket/retail/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/egregors/Documents/Bitbucket/retail/config/urls.py", line 29, in <module>
    from retail.order.views import BundleViewSet, OrderHomeView, OrderDetailView, OrderViewSet, \
  File "/Users/egregors/Documents/Bitbucket/retail/retail/order/views.py", line 18, in <module>
    from retail.order.filters import OrderFilter
  File "/Users/egregors/Documents/Bitbucket/retail/retail/order/filters.py", line 9, in <module>
    class OrderFilter(filters.FilterSet):
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/rest_framework_filters/filterset.py", line 19, in __new__
    new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django_filters/filterset.py", line 90, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/Users/egregors/Documents/Bitbucket/retail/env/lib/python3.6/site-packages/django_filters/filterset.py", line 320, in get_filters
    filter_name = cls.get_filter_name(field_name, lookup_expr)
TypeError: get_filter_name() takes 2 positional arguments but 3 were given
```

**Comment by danielhers** [comment] 2017-10-19 13:58
Duplicate of #187.

**Closed** 2017-10-19 17:03 UTC

**Comment by rpkilby** [comment] 2017-10-20 20:17
v0.10.2 is no on pypi
