### ISSUE TITLE
Multiple exclusions not working

### ISSUE THREAD

**Issue by ericntd** [philipn/django-rest-framework-filters#90] opened 2016-05-17 04:51 UTC
neither `/myapi/articles/?tags__contains=Tag 1&tags__contains=Tag 2` nor `/myapi/articles/?tags__icontains=Tag 1&tags__icontains=Tag 2` works

`/myapi/articles/?tags__contains=Tag 1&tags__icontains=Tag 2` works however

**Comment by rpkilby** [comment] 2016-05-25 03:13
Hi @ericntd, we can't really help without more information from you. Could you provide a more complete reproduction? A code snippet is helpful, but forking the repo and writing a test that demonstrates the problem is even better.

**Comment by rpkilby** [comment] 2016-06-05 21:56
Hi @ericntd - I'm closing this for now as there isn't enough actionable information.

**Closed by rpkilby** 2016-06-05 21:56 UTC
