### ISSUE TITLE
can't import viewsets

### ISSUE THREAD

**Issue by nareshku** [philipn/django-rest-framework-filters#160] opened 2017-01-27 22:32 UTC
Somehow I couldn't import viewsets anymore.

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
     ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
     ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_filters.backends.DjangoFilterBackend',
   ),
}
```

```
python manage.py shell
Python 2.7.6 (default, Jan 27 2017, 05:17:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from rest_framework import viewsets, routers
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/py27/lib/python2.7/site-packages/rest_framework/viewsets.py", line 26, in <module>
    from rest_framework import generics, mixins, views
  File "/opt/py27/lib/python2.7/site-packages/rest_framework/generics.py", line 25, in <module>
    class GenericAPIView(views.APIView):
  File "/opt/py27/lib/python2.7/site-packages/rest_framework/generics.py", line 44, in GenericAPIView
    filter_backends = api_settings.DEFAULT_FILTER_BACKENDS
  File "/opt/py27/lib/python2.7/site-packages/rest_framework/settings.py", line 211, in __getattr__
    val = perform_import(val, attr)
  File "/opt/py27/lib/python2.7/site-packages/rest_framework/settings.py", line 156, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/opt/py27/lib/python2.7/site-packages/rest_framework/settings.py", line 168, in import_from_string
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/py27/lib/python2.7/site-packages/rest_framework_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/opt/py27/lib/python2.7/site-packages/rest_framework_filters/filterset.py", line 117, in <module>
    class FilterSet(six.with_metaclass(FilterSetMetaclass, filterset.FilterSet)):
  File "/opt/py27/lib/python2.7/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/opt/py27/lib/python2.7/site-packages/rest_framework_filters/filterset.py", line 39, in __new__
    new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/opt/py27/lib/python2.7/site-packages/django_filters/filterset.py", line 85, in __new__
    new_class.base_filters = new_class.get_filters()
TypeError: Error when calling the metaclass bases
    unbound method get_filters() must be called with FilterSet instance as first argument (got nothing instead)
>>>
```

**Comment by rpkilby** [comment] 2017-01-28 00:41
This seems like a duplicate of #155. Let me know if that's not the case.

**Closed by rpkilby** 2017-01-28 00:41 UTC

**Comment by nareshku** [comment] 2017-01-30 19:13
I think this issue is different. Here are the installed pip packages.

django-filter (0.13.0)
djangorestframework (3.3.3)
djangorestframework-filters (0.8.0)

**Comment by rpkilby** [comment] 2017-01-31 07:51
I would double check your path. 

```python
  File "/opt/py27/lib/python2.7/site-packages/django_filters/filterset.py", line 85, in __new__
    new_class.base_filters = new_class.get_filters()
```
The above only exists in django-filter 1.0
