### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Detonavomek** [philipn/django-rest-framework-filters#131] opened 2016-10-28 17:48 UTC
Hi 

I have performance issue.

Model have 20 fields and 4 relation for other models with 5 fields. There are near 100 objects.

Without filters API loads 0.4s.
With django_filters by all fields and relations - 0.6s.
With django-rest-framework-filters by all fields(each field has '**all**' lookup) - 7.2s.

In each case I tried to get list of objects without filtering.

Did you test the speed of filtering?

**Comment by rpkilby** [comment] 2016-10-29 15:28
Hi @Detonavomek. A couple of thoughts:
- Is this the initial load or when actually filtering?
- Are you using the backend provided by this package (`rest_framework_filters.backends. DjangoFilterBackend`)? It caches filtersets, which significantly increases performance. 
  - Does a subsequent load/filter run more quickly?

In general, I highly recommend **not** using `AllLookupsFilter`. It's useful for development, but as you solidify your API, I would narrow this down to a smaller list of known, useful lookups.

The problem is that the base model field has 18 different lookups. Other fields (namely the date/time fields) have lookup transforms that have a multiplying effect on that number. For example, `DateTimeField` has the base 18 fields, but 13 date/time transforms that support all of the base lookups. This comes out to a whopping 234 different lookup expressions for just one field.

Even without datetime fields, enabling all lookups can quickly become very expensive. Those 18 lookups x 20 fields totals up to 360 filter instances. On top of this, you have 4 relations which add another 388 filters (at a minimum, the 5 x 18 filters per model, plus another 7 for the FK relation itself). In total, your model should have something close to ~750 filters. And of course, add an additional ~220 filters for every datetime field you're using.

**Comment by Detonavomek** [comment] 2016-10-31 13:41
@rpkilby , thank you for detailed response!

It is time to load each request(not only first). Looks like filterset doesn't cached.
Yes, I use 'rest_framework_filters.backends. DjangoFilterBackend' as a base class.

**Comment by rpkilby** [comment] 2016-10-31 17:37
Hm. I'll have to look into it. The caching should make duplicate requests significantly less expensive. Either way, the fundamental problem is the large number of filters.

**Comment by rpkilby** [comment] 2016-11-12 01:40
Hi @Detonavomek - I've added some rudimentary performance tests in #138.

**Comment by mlissner** [comment] 2017-04-20 23:23
@Detonavomek Could it be that you were testing using the browsable API? I discovered that with filters enabled, the browsable API makes one query per related *object*. So say you have books with authors, and you have 10,000 authors. That will require 10k look ups when you load the book endpoint in the browsable API. Outside of the browsable API, this isn't the case. I'll file a separate bug if this isn't what happened to you, but right now, this means I have to choose between the browsable API and the filters provided here. Not a good choice.

**Comment by bkovacev** [comment] 2017-06-15 22:21
You should use django-debug-toolbar to discover that. Use prefetch related or select related to make sure to exterminate Django ORM lazyness.

**Comment by rpkilby** [comment] 2017-12-30 05:22
I'm going to close this for now, as we have some basic performance tests that help ensure that drf-filters performs within the same realm of efficiency as django-filter.

**Closed by rpkilby** 2017-12-30 05:22 UTC
