### ISSUE TITLE
Travis failures with django-filter 1.0.1

### ISSUE THREAD

**Issue by edmorley** [philipn/django-rest-framework-filters#153] opened 2016-12-27 03:52 UTC
The last Travis run on master was green:
https://travis-ci.org/philipn/django-rest-framework-filters/jobs/176898665

However a newer run on a PR that only updates changelog.rst is now failing on Python 2.7/3.4 (but not 3.5):
https://travis-ci.org/philipn/django-rest-framework-filters/jobs/186893153

One difference between the runs appears to be that the latter is using django-filter 1.0.1 vs 1.0.0.

Changelog:
https://github.com/carltongibson/django-filter/compare/1.0.0...1.0.1

I'm guessing django-rest-framework-filters needs to adjust to:
https://github.com/carltongibson/django-filter/commit/d5516f9828fd7ab5e59359ad6ade5fa5bcbbb949

**Comment by rpkilby** [comment] 2016-12-27 19:29
That commit seems to be it - `rest_framework` isn't resolving. Relevant portion of the stack trace:

```py
Traceback (most recent call last):
  File "./django-rest-framework-filters/tests/test_regressions.py", line 25, in <module>
    from .testapp.filters import (
  File "./django-rest-framework-filters/tests/testapp/filters.py", line 3, in <module>
    from rest_framework_filters import filters
  File "./django-rest-framework-filters/rest_framework_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "./django-rest-framework-filters/rest_framework_filters/filterset.py", line 74, in <module>
    class FilterSet(six.with_metaclass(FilterSetMetaclass, rest_framework.FilterSet)):
AttributeError: 'NoneType' object has no attribute 'FilterSet'
```

**Comment by rpkilby** [comment] 2016-12-27 21:49
For now, #154 fixes this by simply adding `django_filters` to `INSTALLED_APPS`.

The test failures are a caused by circular *relative* imports, which are not supported in python 3.4 and below ([py35 changelog](https://docs.python.org/3/whatsnew/3.5.html#other-language-changes)). I've tried creating a test case for django-filter that demonstrates the issue, but haven't been able to so. 

I think the correct thing to do here is to revert the referenced commit. However, I cannot justify the reversion without the test case.

**Closed by rpkilby** 2016-12-27 21:49 UTC
