### ISSUE TITLE
Version 0.10.1 has an exception when used with django-filter 1.1

### ISSUE THREAD

**Issue by hmpf** [philipn/django-rest-framework-filters#202] opened 2017-11-07 13:50 UTC
If I run django-rest-framework-filters 0.10.1 on top of django-filter 1.10 I get the following exception:

```
  File "/../python3.5/site-packages/rest_framework_filters/backends.py", line 19, in get_subset_class
    filter_class = original(view, queryset)
  File "/../python3.5/site-packages/django_filters/rest_framework/backends.py", line 41, in get_filter_class
    class AutoFilterSet(self.default_filter_set):
  File "/../python3.5/site-packages/rest_framework_filters/filterset.py", line 19, in __new__
    new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/../python3.5/site-packages/django_filters/filterset.py", line 90, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/../python3.5/site-packages/django_filters/filterset.py", line 320, in get_filters
    filter_name = cls.get_filter_name(field_name, lookup_expr)
TypeError: get_filter_name() takes 2 positional arguments but 3 were given
```
Downgrading django-filters to 1.0.4 solves the issue.

**Comment by rpkilby** [comment] 2017-11-07 13:57
Hi @hmpf - this is a duplicate of #187 and has already been fixed by #189. You need to upgrade to the v0.10.2 release.

**Closed by rpkilby** 2017-11-07 13:57 UTC
